name: "Checks README"

on:
  push:
    paths:
      - 'README.md'
      - 'words.dic'
      - '.github/workflows/check-readme.yml'

  pull_request:
    paths:
      - 'README.md'
      - 'words.dic'
      - '.github/workflows/check-readme.yml'
      
jobs:
  SpellCheckReadme:
    runs-on: ubuntu-latest

    container:
      image: perl:5.28

    steps:
      - name: Prerrequisites
        run: |
          apt-get update && apt-get upgrade -y && apt-get install -y libtext-hunspell-perl
      - uses: actions/checkout@v2
      - name: Install modules from CPAN
        uses: perl-actions/install-with-cpm@stable
        with:
          install: TAP::Harness
          sudo: false
      - name: Checks spelling
        run: |
          echo "use lib qw(lib); use Test::Text; just_check( '.','data', 'en_US' ); " > just_check.t
          perl -MTAP::Harness -e 'use utf8; my $harness = TAP::Harness->new( { verbosity => 0} ); die "FAIL" if $harness->runtests( "just_check.t" )->failed;'
